import { Badge } from '@/components/ui/badge'

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white rounded-lg shadow-sm p-8 md:p-12">
          <Badge className="mb-4 bg-[#743181]">Legal</Badge>
          <h1 className="text-4xl font-bold text-gray-900 mb-8 font-serif">Terms and Conditions</h1>
          
          <div className="prose prose-pink max-w-none text-gray-600 space-y-6">
            <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

            <p>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://sarvaasweetsandcakes.com/" className="text-[#743181] hover:underline">https://sarvaasweetsandcakes.com/</a> ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").</p>

            <p>The Platform is owned by <strong>SARVAA SWEETS</strong>, a company incorporated under the Companies Act, 1956 with its registered office at GROUND FLOOR, H-25, ERODE TOWN, EVN ROAD, Erode Periyar Nagar, Erode, India (hereinafter referred to as “Platform Owner”, "we", "us", "our").</p>

            <p>Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.</p>

            <p>These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, "Services"). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>

            <p>For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>

            <p className="font-bold text-gray-900 border-l-4 border-[#743181] pl-4">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </p>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Use of Platform and Services</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
                <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
                <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</li>
                <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.</li>
                <li>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
                <li>You agree to pay us the charges associated with availing the Services.</li>
                <li>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
                <li>The website and Services may contain links to third party websites. Accessing these links will subject you to their terms and privacy policies. These are provided for convenience only.</li>
                <li>You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner.</li>
                <li>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies, and their respective officers, directors, agents, and employees from any claims or demands arising from your breach of these Terms or violation of any law or third-party rights.</li>
                <li>Platform Owner shall not be liable for any failure to perform an obligation under these Terms if such performance is prevented or delayed by a force majeure event.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Governing Law and Jurisdiction</h2>
              <p>These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Erode, Tamil Nadu.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
              <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
